# Generated by Django 6.0 on 2025-12-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='talon',
            name='is_free',
            field=models.BooleanField(default=True),
        ),
    ]
